id: PBB03C44F
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA00EGS1016963
  instance_id: http://purl.bdrc.io/resource/IE1KG4280
  collection_id: http://purl.bdrc.io/resource/PR0ET001
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གསུང་འབུམ། པདྨ་ཉིན་བྱེད་དབང་པོ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P559
  publisher: DharmaDownload
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    8bb37bedc61c4a70bc5038ab88b3034f:
      title: ༄༅།་།ཨོ་རྒྱན་རིན་པོ་ཆེ་བདེ་གཤེགས་སྤྱི་དྲིལ་དུ་བསྒྲུབས་པའི་རྣལ་འབྱོར་གྲུབ་གཉིས་ནོར་བུའི་ཆར་འབེབས་ཞེས་བྱ་བ་བཞུགས་སོ།་།
      volume_number: 3
      base_file: UT1KG4280_003_0003.txt
      reference: http://purl.bdrc.io/resource/VL8030E131BDAFCAB7
      image_group: null
      quality: null
    716132d357f64dbe965cf2193f858d7f:
      title: ༄༅།་།ཇོ་བོ་སྔགས་ཀྱི་བདག་པོའི་གཡང་སྐྱབས་དངོས་གྲུབ་འབྱུང་བའི་རྒྱ་མཚོ་ཞེས་བྱ་བ་བཞུགས་སོ།་།
      volume_number: 1
      base_file: UT1KG4280_001_0019.txt
      reference: http://purl.bdrc.io/resource/VLDE7E67BBC01E8408
      image_group: null
      quality: null
    a672a76f73894009a217d77779b51b5f:
      title: ༄༅།་།བསང་མཆོད་ཀྱི་རིམ་པ་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་ཕན་བདེ་བདུད་རྩིའི་གཏེར་མཛོད་ཅེས་བྱ་བ་བཞུགས་སོ།་།
      volume_number: 2
      base_file: UT1KG4280_002_0002.txt
      reference: http://purl.bdrc.io/resource/VL9DF6A6211803DA47
      image_group: null
      quality: null
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG4280
  - http://purl.bdrc.io/resource/MW1KG4280
created_at: '2021-12-24T17:18:41.374854'
last_modified_at: '2021-12-24T17:18:41.374865'
